// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQvzF0hSWByQka17vOSS8GHXtBWaSSYM',
    appId: '1:267541247153:web:253fabaa637900a5cc1e90',
    messagingSenderId: '267541247153',
    projectId: 'viva-contact-app',
    authDomain: 'viva-contact-app.firebaseapp.com',
    storageBucket: 'viva-contact-app.appspot.com',
    measurementId: 'G-MZ9ZEL4YW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdX4YXPwA4eiOZoymovIf0c-0xw-WUIqo',
    appId: '1:267541247153:android:8b5ee1cc6eec48d6cc1e90',
    messagingSenderId: '267541247153',
    projectId: 'viva-contact-app',
    storageBucket: 'viva-contact-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFpJSnCURgcanrCZGZZnmnLLwtWEZIap0',
    appId: '1:267541247153:ios:2d813c3bb6b3ca67cc1e90',
    messagingSenderId: '267541247153',
    projectId: 'viva-contact-app',
    storageBucket: 'viva-contact-app.appspot.com',
    iosBundleId: 'com.example.vivaContactApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFpJSnCURgcanrCZGZZnmnLLwtWEZIap0',
    appId: '1:267541247153:ios:b7b2fc3b76f2b840cc1e90',
    messagingSenderId: '267541247153',
    projectId: 'viva-contact-app',
    storageBucket: 'viva-contact-app.appspot.com',
    iosBundleId: 'com.example.vivaContactApp.RunnerTests',
  );
}
